name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy containers
        run: |
          cd containers
          ./deploy
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  deploy-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy packages
        run: |
          cd packages
          ./deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: deploy cli
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd cli
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/*
