name: deploy-lesspass-crypto-package

on:
  push:
    paths:
      - "packages/lesspass-crypto/**"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: test lesspass-crypto package
        run: |
          yarn install
          yarn workspace lesspass-crypto run test

  deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: deploy lesspass-crypto package
        run: |
          cd packages
          ./deploy lesspass-crypto
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
