name: lesspass-fingerprint-test
on:
  push:
    paths:
      - "packages/lesspass-fingerprint/**"
  pull_request:
    paths:
      - "packages/lesspass-fingerprint/**"
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn workspace lesspass-crypto run build
      - run: yarn workspace lesspass-fingerprint run test
