name: test

on: [push, pull_request]

jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test packages
        run: |
          yarn install
          yarn test

  test-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test mobile
        run: |
          cd mobile
          yarn install
          yarn test

  test-cli:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.5, 3.6, 3.7]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: test cli
        run: |
          cd cli
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r test-requirements.txt
          export PYTHONPATH='.'
          python -m unittest discover

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: test backend
        run: |
          cd containers/backend
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py test
